try check secret key
Signed-off-by: yifengyou <842056007@qq.com>

diff --git a/.github/workflows/build-am60.yml b/.github/workflows/build-am60.yml
--- a/.github/workflows/build-am60.yml
+++ b/.github/workflows/build-am60.yml
@@ -118,6 +118,16 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v4
 
+      - name: check GITHUB_TOKEN
+        id: check_token
+        run: |
+          if [ -z "${{ secrets.GITHUB_TOKEN }}" ]; then
+            echo "GITHUB_TOKEN not set, abort"
+            exit 1
+          else
+            echo "GITHUB_TOKEN already set."
+          fi
+
       - name: Initialization environment
         id: init
         env:
